version: '3.7'
services:
  node:
    image: trancelife/subspace-node:latest
    networks:
      - sp_network
    ports:
      - "0.0.0.0:21168:21168/tcp"
      - "0.0.0.0:21168:21168/udp"
      - "0.0.0.0:21165:21165/tcp"
      - "0.0.0.0:21165:21165/udp"
      - "0.0.0.0:8934:8934"
    privileged: true
    volumes:
      - ./node_data:/app/node_data
    environment:
      - NODE_NAME=${NODE_NAME:?please make sure to set your NODE_NAME environment variable in the .env file}
    command:
      - "--chain"
      - "mainnet"
      - "--base-path"
      - "/app/node_data"
      - "--listen-on"
      - "/ip4/0.0.0.0/tcp/21165"
      - "--dsn-listen-on"
      - "/ip4/0.0.0.0/tcp/21168"
      - "--dsn-listen-on"
      - "/ip4/0.0.0.0/udp/21168/quic-v1"
      - "--rpc-listen-on"
      - "0.0.0.0:8934"
      - "--rpc-cors"
      - "all"
      - "--rpc-methods"
      - "unsafe"
      - "--farmer"
    restart: unless-stopped

networks:
  sp_network:
