version: '3.7'
services:
  farmer:
    image: subspace-farmer
    networks:
      - sp_network
    ports:
      - "30533:30533"
    privileged: true
    volumes:
      - ${PLOT_PATH:-./data}:/app/plot
    environment:
      - REWARD_ADDRESS=${REWARD_ADDRESS:?please make sure to set your REWARD_ADDRESS environment variable in the .env file}
      - NODE_RPC_URL=${NODE_RPC_URL}
      - PLOT_SIZE=${PLOT_SIZE:?please make sure to set your PLOT_SIZE environment variable in the .env file}
    command:
      - "--farm-during-initial-plotting"
      # 这里可以添加其他参数，添加其他path,注意添加path要在volumes映射
      # - "path=/subspace2,size=100G"
      # - "--cache-percentage"
      # - "2"
      # - "--listen-on"
      # - "/ip4/0.0.0.0/tcp/30533"
    restart: unless-stopped
  
  # node:
  #   image: subspace-node
  #   networks:
  #     - sp_network
  #   ports:
  #     - "0.0.0.0:30333:30333/tcp"
  #     - "0.0.0.0:30333:30333/udp"
  #     - "0.0.0.0:30433:30433/tcp"
  #     - "0.0.0.0:30433:30433/udp"
  #     - "0.0.0.0:9944:9944"
  #   privileged: true
  #   volumes:
  #     - ${NODE_BASE_PATH:-./node_data}:/app/node_data
  #   environment:
  #     - NODE_BASE_PATH=${NODE_BASE_PATH:?please make sure to set your NODE_BASE_PATH environment variable in the .env file}
  #     - NODE_NAME=${NODE_NAME:?please make sure to set your NODE_NAME environment variable in the .env file}
  #   command:
  #     - "--chain"
  #     - "gemini-3g"
  #     - "--base-path"
  #     - "/app/node_data"
  #     - "--blocks-pruning"
  #     - "256"
  #     - "--state-pruning"
  #     - "archive-canonical"
  #     - "--port"
  #     - "30333"
  #     - "--dsn-listen-on"
  #     - "/ip4/0.0.0.0/tcp/30433"
  #     - "--rpc-cors"
  #     - "all"
  #     - "--rpc-methods"
  #     - "unsafe"
  #     - "--unsafe-rpc-external"
  #     - "--validator"
  #   restart: unless-stopped

networks:
  sp_network:
